config/routes.rb
Triviadojo::Application.routes.draw do
  get "custom_games/new"
  post "custom_games/content"
  resources :users
  resources :questions
  get "games/new"
  post "games/play", to: "games#play"
  post "games/check_answer"
  post "games/get_question"
  post "games/submit_score"

  resources :sessions, :only => [:new, :create, :destroy]
  
  get "static_pages/home"
  post "static_pages/submit"
  root to: 'static_pages#home'
  
  get '/signup',  to: 'users#new'
  get '/about',   to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/create',   to: 'custom_games#welcome'
  get "/signin",  to: 'sessions#new'
  delete "/signout", to: 'sessions#destroy'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :questions
	has_many :scores
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :category
	validates :category_id, presence: true
	has_many :answers
end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	before_save :create_remember_token

	validates :first_name, :last_name,  presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_many :scores

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/missing.jpg"

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/custom_games_controller.rb
class CustomGamesController < ApplicationController
	# before_action :signed_in_user, only: [:new, :content]

	def new
	end

	def content
	end

	def create
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def new
  end

  def play
  	@category = params[:category].capitalize
    cat = Category.find_by(name: params[:category])
    @category_id = cat.id
    @count = params[:number_of_questions].to_i
  	@@questions = cat.questions.sample(@count)
    @@answers, @@correct_answers = [], []
    # This will do an for loop around the each individual answer base on the unique question id
    # @@question.map(&:id) is the same as @@question.map(|x| x.id).  Which create a separate array with only the question id
    Answer.where(question_id: @@questions.map(&:id)).each do |a|
      # @@answers = [answers for question id]
      @@answers << a
      @@correct_answers << a.id if a.correct == 1
    end
    @@answers.shuffle!
  end

  def get_question
    question = @@questions[params[:index].to_i]
    data = { question: question }
    data[:answers] = @@answers.select { |a| a.question_id == question.id }
    respond_to do |format|
      format.json { render json: data }
    end
  end

  def check_answer
    answer = params[:answer].to_i
    data = @@correct_answers.include?(answer)
  	respond_to do |format|
      format.json { render json: data }
    end
  end

  def submit_score
    @score = Score.new(score_params)
    if @score.save
      data = ''
      respond_to do |format|
        format.json { render json: data }
      end
    end
  end

  private

    def score_params
      params.permit(:number_correct, :number_attempted, :user_id, :category_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
	end

	def new
	end

	def create
		if current_user.admin?
			category = Category.find_by(name: params[:category])
			question = category.questions.create(content: params[:question])
			question.answers.create(content: params[:answer1], correct: 1)
			question.answers.create(content: params[:answer2], correct: 0)
			question.answers.create(content: params[:answer3], correct: 0)
			question.answers.create(content: params[:answer4], correct: 0)
			answers = [params[:answer1], params[:answer2], params[:answer3], params[:answer4]]
			ContactMailer.submit_question(current_user.email, params[:category], params[:question], answers).deliver
			flash[:success] = "The question has been added!  Thank you!"
			redirect_to current_user
		else
			ContactMailer.submit_question(current_user.email, params[:category], params[:question], params[:answer]).deliver
			flash[:success] = "Thank you for contributing to TriviaDojo with your knowledge!"
			redirect_to current_user
		end
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def about
	end

	def contact
	end

	def submit
		ContactMailer.feedback_email(params[:name], params[:email], params[:type], params[:message]).deliver
		flash[:success] = "Thank you for submitting, we will get back to you promptly."
		render 'contact'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :admin_user,     only: :destroy

	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
    if @user.save
    	UserMailer.welcome_email(@user).deliver
      sign_in @user
      flash[:success] = "Welcome to TriviaDojo!"
      redirect_to @user
    else
      render 'new'
    end
	end

	def show
		@categories = Category.all
		@scores = @user.scores
		@total_correct = @scores.inject(0){ |sum, x| sum+x.number_correct}
		@total_attempted = @scores.inject(0){ |sum, x| sum+x.number_attempted}
		@average = @total_correct / @total_attempted.to_f * 100
	end

	def edit
	end

	def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
	end

	def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
	end
	
	private

	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
	  end

	  def correct_user
	    @user = User.find(params[:id])
	    redirect_to(root_path) unless current_user?(@user)
	  end

	  def admin_user
	    redirect_to(root_path) unless current_user.admin?
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_games_helper.rb
module CustomGamesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/custom_games/content.html.erb
<% provide(:title, 'Create a trivia!') %>

<div class="container customer_games_content">
	<div class="row">
		<div class="span7 offset2">
			<div class="page-header">
				<h1>Create your own Trivia</h1>
			</div>
			<div class="row">
				<div class="span6">
					<form action="/customize_games/content" method="post">
						<h2 style="color:orange">Step 2: What are your questions?</h2><br/>
						<h3>Questions 1 of</h3><br/>
						<h4>Content:</h4>
						<textarea name="question" cols="30" rows="8" placeholder="e.g: Who is NOT both a Heisman Trophy winner and a former number one overall pick in the NFL draft?"></textarea>
						<h4>Answers: <span style="color:red; font-size:12px">*In actual quiz the answers will be shuffled*</span></h4>
						<span style="color:red; font-weight:bold">Correct Answer: </span><input class="answer_input" type="text" name="answer1" placeholder="Answer 1">
						<span style="font-weight:bold">Wrong Answer: &nbsp;</span><input class="answer_input" type="text" name="answer2" placeholder="Answer 2">
						<span style="font-weight:bold">Wrong Answer: &nbsp;</span><input class="answer_input" type="text" name="answer3" placeholder="Answer 3">
						<span style="font-weight:bold">Wrong Answer: &nbsp;</span><input class="answer_input" type="text" name="answer4" placeholder="Answer 4"><br/><br/>
						<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
						<input type="submit" value="Next" class="btn btn-large btn-primary">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/custom_games/new.html.erb
<% provide(:title, 'Create a trivia!') %>

<div class="container customer_games_new">
	<div class="row">
		<div class="span7 offset2">
			<div class="page-header">
				<h1>Create your own Trivia</h1>
			</div>
			<form action="/custom_games/content" method="post">
				<div class="row">
					<div class="span6">
						<h2 style="color:orange">Step 1: Why create one?</h2><br/>
						<h4>What is the category or occasion?</h4>
						<input type="text" name="category" placeholder="Category or Occasion"><br/><br/>
						<h4>Number of Questions</h4>
						<input type="text" name="number_of_questions" placeholder="Up to 30"><br/><br/>
						<h4>How much time per question?</h4>
						<input type="text" name="time_per_question" placeholder="20 seconds?"><br/>
					</div>
				</div>
				<br/>
				<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
				<input type="submit" value="Fill in the questions!" class="btn btn-large btn-primary">
			</form>
		</div>
	</div>
</div>

app/views/custom_games/welcome.html.erb
<% provide(:title, "Create Questions") %>

<div class="container create_page">
	<div class="page-header">
  	<h1>Create your own trivia <small>OR</small> Add to our pool of questions</h1>
	</div>
	<div class="container">
		<div class="row">
			<div class="span5 offset1">
				<ul class="thumbnails">
				  <li class="span4">
				    <div class="thumbnail">
				      <img src="/assets/question1.jpg" alt="">
				      <h3>Create a custom trivia</h3>
				      <p>Have a party? Want to host private questionaire or quiz?  This will enable to create you a trivia with a specific category and only send it to a set list of individuals.</p>
							<% if signed_in? %>
				      	<a href="" class="btn btn-block btn-primary">Create Now</a>
				      <% else %>
				      	<a href="/signin" class="btn btn-block btn-primary">Sign In</a>
				      <% end %>
				    </div>
				  </li>
				</ul>
			</div>
			<div class="span5">
				<ul class="thumbnails">
				  <li class="span4">
				    <div class="thumbnail">
				      <img src="/assets/question2.jpg" alt="">
				      <h3>Suggest a new question</h3>
				      <p>You are a world trivia genius, and you look forward to share that knowledge with the TriviaDojo Community.  Click the button and suggest away!</p><br/>
				    </div>
				    <% if signed_in? %>
				      <a href="/questions/new" class="btn btn-block btn-primary">Suggest Away</a>
				    <% else %>
				    	<a href="/signin" class="btn btn-block btn-primary">Sign In</a>
				    <% end %>
				  </li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/games/new.html.erb
<% provide(:title, 'Play Game!') %>

<div class="container games_new">
	<div class="row">
		<div class="span7 offset2">
			<div class="page-header">
				<h1>Select your trivia of interest</h1>
			</div>
			<form action="/games/play" method="post">
				<div class="row">
					<div class="span3">
						<h3>Category</h3>
						<select name="category">
							<option value="sports">Sports</option>
							<option value="pop_culture">Pop Culture</option>
							<option value="history">History</option>
							<option value="News">News</option>
							<option value="Movies">Movies</option>
						</select>
					</div>
					<div class="span3 offset1">
						<h3>Number of Questions</h3>
						<select name="number_of_questions">
							<option value="5">5</option>
							<option value="10">10</option>
							<option value="15">15</option>
							<option value="20">20</option>
						</select>
					</div>
				</div>
				<br/>
				<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
				<input type="submit" value="Let's get started!" class="btn btn-large btn-block btn-primary">
			</form>
		</div>
	</div>
</div>

app/views/games/play.html.erb
<% provide(:title, 'Play Game!') %>
<% content_for :javascript do %>
<script>
$(document).ready(function() {

	var score = 0;
	var index = 0;
	var count = <%= @count %>;

	function outputQuestion() {
		if (index == count) {
			<% if signed_in? %>
				$('#number_correct').val(score);
				$('#number_attempted').val(count);
				$('#user_id').val(<%= current_user.id %>);
				$('#category_id').val(<%= @category_id %>);
				var form = $('#score_form');
				$.post(form.attr('action'), form.serialize(), function() {
				});
			<% end %>
			$('#question_content').empty();
			$('#result').empty();
			$('#question').html("<h3>Final score: " + score + "/" + count + "</h3>");
		} 
		else {
			$('#index').val(index);
			var form = $('#question_form');
			$.post(form.attr('action'), form.serialize(), function(data) {
				$('#question_content').html(data.question.content);
				for (var i = 0; i < 4; i++) {
					var answer = data.answers[i];
					$('#answer_input' + i).val(answer.id);
					$('#answer_content' + i).html(answer.content);
				}
			});
			$('#notification').empty().removeClass("alert alert-success alert-error");
			attachAnswerEvents();
			$('#button_div').empty();
		}
	}

	function attachAnswerEvents() {	
		$('.answer').css('opacity', 1);
		$('.answer').on({
			click: function() {
				checkAnswer($(this));
			},
			mouseenter: function() {
				$(this).css({
					opacity: .5,
					cursor: 'pointer'
				});
			},
			mouseleave: function() {
				$(this).css('opacity', 1);
			}
		});
	}

	function checkAnswer(element) {
		$('.answer').off().css('cursor', 'auto');
		var form = element.children();
		$.post(form.attr('action'), form.serialize(), function(data) {
			if (data) {
				score++;
				$('#notification').addClass("alert alert-success");
				$('#notification').html("Correct!");
			} else {
				$('#notification').addClass("alert alert-error");
				$('#notification').html("Wrong Answer!");
			}
		});
		$('#button_div').html("<button id='next' class='btn btn-primary'>Next Question</button>");
		$('#next').click(function() {
			index++;
			outputQuestion();
		});
	}

	outputQuestion();

});
</script>
<% end %>

<div class="container">
	<div class="row">
		<h1 id="game_title" class="span10 offset1"><%= @category %> Trivia Game</h1>
		<h4 id="question_content" class="span4 offset1"></h4>
		<div id="question" class="span4 offset1">
				<form id="question_form" action="/games/get_question" method="post">
					<input type="hidden" name="authenticity_token" value="token_value">
					<input id="index" type="hidden" name="index">
				</form>
				
				<% (0..3).each do |i| %>
					<div class="answer alert alert-info">
						<form action="/games/check_answer" method="post">
							<input type="hidden" name="authenticity_token" value="token_value">
							<input id="answer_input<%= i %>" type="hidden" name="answer">
							<p id="answer_content<%= i %>"></p>
						</form>
					</div>
				<% end %>

				<form id="score_form" action="/games/submit_score" method="post">
					<input type="hidden" name="authenticity_token" value="token_value">
					<input id="number_correct" type="hidden" name="number_correct">
					<input id="number_attempted" type="hidden" name="number_attempted">
					<input id="user_id" type="hidden" name="user_id">
					<input id="category_id" type="hidden" name="category_id">
				</form>
		</div>
		<div id="result" class="span4 offset1">
			<h4 id="notification" class="alert-block"></h4>
			<div id="button_div">
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<hr class="footer-divider">
<div class="container">
  <p style="text-align: center">
    &copy; 2013 TriviaDojo, Inc. All Rights Reserved.
  </p>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "TriviaDojo", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
      		<li class="divider-vertical"></li>
      		<li><%= link_to "Play", games_new_path %></li>
      		<li class="divider-vertical"></li>
      		<li><%= link_to "Create", create_path %></li>
      		<li class="divider-vertical"></li>
<!--       		<li><%= link_to "About us", about_path %></li>
      		<li class="divider-vertical"></li> -->
      		<li><%= link_to "Contact us", contact_path %></li>
      		<li class="divider-vertical"></li>
          <% if !signed_in? %>
      		<li><%= link_to "Sign up", signup_path %></li>
      		<li class="divider-vertical"></li>
          <% end %>
      	</ul>
        <% if signed_in? %>
          <ul class="nav pull-right">
            <li><a href="/users/<%= current_user.id %>"><%= current_user.first_name %> <%= current_user.last_name %></a></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= form_for :session, :url => sessions_path, :html => {class: "navbar-form pull-right"} do |f| %>

            <%= f.text_field :email, placeholder: "Email", class: "span2" %>

            <%= f.password_field :password, placeholder: "Password", class: "span2"  %>

            <%= f.submit "Sign In", class: "btn"%>
          <% end %>
        <% end %>
      </div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Triviadojo | <%= yield :title %> </title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= tag :meta, name: "viewport", content: "width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" %>
    <%= tag :meta, name: "HandheldFriendly", content: "true" %>
	  <%= render 'layouts/shim' %>
    <%= yield :javascript %> 
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container" style="margin-top: 50px;">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
						<button type="button" class="close" data-dismiss="alert">&times;</button>
          	<%= value %>
          </div>
        <% end %>
    </div>
		<%= yield %>
	</body>
	<footer>
	<%= render 'layouts/footer' %>
	</footer>	
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div id="myCarousel" class="carousel slide">
	<div class="carousel-inner">
		<div class="item active">
			<img src="/assets/home1.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>A place you can play Trivia, or even create one of your own!</h1>
					<%= link_to "Play Now", games_new_path, class: "btn btn-large btn-primary" %>
				</div>
			</div>
		</div>
		<div class="item">
			<img src="/assets/home2.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>Ready to be a trivia master? Sign in and conquer our campaigns!</h1>
					<%= link_to "Sign In", signin_path, class: "btn btn-large btn-primary" %>
				</div>
			</div>
		</div>
		<div class="item">
			<img src="/assets/home3.jpg">
			<div class="container">
				<div class="carousel-caption">
					<h1>Create your own private or public trivia for events or celebrations!</h1>
					<%= link_to "Sign In", signin_path, class: "btn btn-large btn-primary" %>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div> <!--End of the Carousel -->

<div class="container home_module">
	<div class="row">
		<div class="span4">
			<h3>Play Trivia</h3>
			<p>With over 50 questions selected at random, you can just select a category and start playing!</p>
			<a href="" class="btn btn-info">Play Now</a>
		</div>
		<div class="span4">
			<h3>Campaign Mode</h3>
			<p><span>*** Coming Soon ***</span><br/>Create an account with us and keep track of your score, and play conquer a list of challenges that we have created for you!</p>
			<%= link_to "Sign In", signin_path, class: "btn btn-info" %>
		</div>
		<div class="span4">
			<h3>Customize Your Trivia</h3>
			<p><span>*** Coming Soon ***</span><br/>Create an account with us and give you the ability to create your own trivia and share it!  It is perfect for party event and even for teachers in class!</p>
			<%= link_to "Sign In", signin_path, class: "btn btn-info" %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<div class="container edit_profile">
	<div class="row">
	  <div class="span5 offset3">
	  	<div class="well">
		  	<h1>Update Your Profile</h1>

		    <%= form_for @user, :url => user_path do |f| %>

		      <%= render 'shared/error_messages', object: f.object %>

		      <%= f.label :first_name %>
		      <%= f.text_field :first_name %>

		      <%= f.label :last_name %>
		      <%= f.text_field :last_name %>

		      <%= f.label :email %>
		      <%= f.text_field :email %>

		      <%= f.label :password %>
		      <%= f.password_field :password %>

		      <%= f.label :password_confirmation %>
		      <%= f.password_field :password_confirmation %>

		      <%= f.file_field :avatar %>

		      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		    <% end %>
		  </div>
	  </div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="container sign_up">
	<div class="row">
	  <div class="span5 offset3">
	  	<div class="well">
		  	<h1>Sign up for TriviaDojo<br/><small>Time to test your knowledge!</small></h1>

		    <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>

		      <%= render 'shared/error_messages', object: f.object %>

		      <%= f.label :first_name %>
		      <%= f.text_field :first_name %>

		      <%= f.label :last_name %>
		      <%= f.text_field :last_name %>

		      <%= f.label :email %>
		      <%= f.text_field :email %>

		      <%= f.label :password %>
		      <%= f.password_field :password %>

		      <%= f.label :password_confirmation %>
		      <%= f.password_field :password_confirmation %>

		      <%= f.file_field :avatar %>

		      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		    <% end %>
		    <p>Already have an account? <%= link_to "Sign in now!", signin_path %></p>
		  </div>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<% content_for :javascript do %>
	<script type="text/javascript">
		$(document).ready(function(){
	    $('#myTab a:first').tab('show');
		});
	</script>
<% end %>

<div class="container">
	<div class="row">
		<div class="span4">
			<h3><%= @user.first_name %> <%= @user.last_name %>'s Profile</h3><br/>
			<%= image_tag @user.avatar.url(:thumb), :style => "margin-left: 10px" %><br/><br/>
			<p><b>Email:</b> <%= @user.email %> <%= link_to "Change", edit_user_path(current_user) %></p>
			<p><b>Password</b> <%= link_to "Change", edit_user_path(current_user) %></p>
			<p><b>Member Since:</b> <%= @user.created_at.strftime("%B %d, %Y") %></p>
			<p><b>Number of Games Played:</b> <%= @scores.count %></p>
		</div>
		<div class="span8">
			<h2>Game Analytics</h2>
			<hr>
			<!-- Analytics Table -->
			<ul class="nav nav-tabs" id="myTab">
				<li class="active"><a href="#scores" data-toggle="tab">Scores</a></li>
				<li><a href="#category" data-toggle="tab">Category</a></li>
				<li><a href="#others" data-toggle="tab">Others</a></li>
			</ul>
			<div class="tab-content">
			  <div class="tab-pane fade active in" id="scores">
			  	<h3>Lifetime Score: <%= @total_correct %>/<%= @total_attempted %>, <%= @average %>% <small><%= @scores.count %> Games</small></h3>
			  	<table class="table table-bordered">
			  		<thead>
			  			<tr>
				  			<th>#</th>
				  			<th>Score</th>
				  			<th>Category</th>
				  			<th>Time</th>
				  		</tr>
			  		</thead>
			  		<tbody>
			  			<% count = 1 %>
			  			<% @scores.each do |s| %>
				  			<tr>
				  				<td><%= count %></td>
				  				<td><%= s.number_correct %>/<%= s.number_attempted %></td>
				  				<% @categories.each do |c| %>
				  					<% if c.id == s.category_id %>
				  						<td><%= c.id %></td>
				  						<% break %>
				  					<% end %>
				  				<% end %>
				  				<td><%= s.created_at %></td>
				  			</tr>
			  				<% count += 1 %>
							<% end %>
			  		</tbody>	
			  	</table>
			  </div> <!-- End of the scores tab in Analytics table -->
				<div class="tab-pane fade" id="category">
			  	<h3><%= @test %></h3>
			  </div> <!-- End of the category tab in Analytics table -->
			  <div class="tab-pane fade" id="others">
			  	<h3>TBD after category</h3>
			  </div> <!-- End of the others tab in Analytics table -->
			</div> <!-- End of the Analytics table -->
	 	</div> <!-- End of span8 -->
	</div> <!-- End of row -->
</div> <!-- End of container -->